dist: trusty
language: node_js
node_js:
  - "7.6.0"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - npm install -g grunt-cli karma-cli
  - npm install
